service: nest-lambda-sample

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true
  tracing:
    lambda: true

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

custom:
  prune:
    automatic: true
    number: 2
  webpack:
    includeModules:
      forceInclude:
        - pg # I'm using postgres
    webpackConfig: ./webpack/webpack.config.js
    packager: 'npm' # Packager that will be used to package your external modules
    excludeFiles: src/**/*.spec.js # Provide a glob for files to ignore